"""Initial schema for LangGraph observability

Revision ID: 419b959712f7
Revises: 
Create Date: 2025-12-06 19:27:14.605676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '419b959712f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('graph_id', sa.String(), nullable=True),
    sa.Column('graph_version', sa.String(), nullable=True),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('input_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_agent_id'), 'runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_runs_framework'), 'runs', ['framework'], unique=False)
    op.create_index(op.f('ix_runs_graph_id'), 'runs', ['graph_id'], unique=False)
    op.create_index(op.f('ix_runs_started_at'), 'runs', ['started_at'], unique=False)
    op.create_index('ix_runs_started_at_desc', 'runs', [sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('from_node', sa.String(), nullable=False),
    sa.Column('to_node', sa.String(), nullable=False),
    sa.Column('condition_label', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_run_id'), 'edges', ['run_id'], unique=False)
    op.create_index('ix_edges_run_order', 'edges', ['run_id', 'order'], unique=False)
    op.create_table('node_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('node_key', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('state_in', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_out', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upstream_node_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_node_exec_run_order', 'node_executions', ['run_id', 'order'], unique=False)
    op.create_index(op.f('ix_node_executions_node_key'), 'node_executions', ['node_key'], unique=False)
    op.create_index(op.f('ix_node_executions_order'), 'node_executions', ['order'], unique=False)
    op.create_index(op.f('ix_node_executions_run_id'), 'node_executions', ['run_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('node_execution_id', sa.String(), nullable=True),
    sa.Column('evaluator', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_automated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['node_execution_id'], ['node_executions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_node_execution_id'), 'evaluations', ['node_execution_id'], unique=False)
    op.create_index(op.f('ix_evaluations_run_id'), 'evaluations', ['run_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('node_execution_id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['node_execution_id'], ['node_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_node_execution_id'), 'messages', ['node_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_node_execution_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_evaluations_run_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_node_execution_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_node_executions_run_id'), table_name='node_executions')
    op.drop_index(op.f('ix_node_executions_order'), table_name='node_executions')
    op.drop_index(op.f('ix_node_executions_node_key'), table_name='node_executions')
    op.drop_index('ix_node_exec_run_order', table_name='node_executions')
    op.drop_table('node_executions')
    op.drop_index('ix_edges_run_order', table_name='edges')
    op.drop_index(op.f('ix_edges_run_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index('ix_runs_started_at_desc', table_name='runs')
    op.drop_index(op.f('ix_runs_started_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_graph_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_framework'), table_name='runs')
    op.drop_index(op.f('ix_runs_agent_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
